name: Actions Workflow

on:
  push:
    branches: [develop]

jobs:
  build:
    name: buildando
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        env: 
          MYSECRET: ${{ secrets.SERVER_SSH_KEY }}
        with:
            password: ${{ secrets.SERVER_SSH_KEY }}
            script: |
              whoami
              echo $PATH

#   if_merged:
#     if: github.event.pull_request.merged == true
#     runs-on: ubuntu-latest
#     steps:
#       - name: List Files
#         run: |
#           pwd
#           ls

#       - name: Checkout
#         uses: actions/checkout@v3

#       - name: List Files After Checkout
#         run: |
#           pwd
#           ls

#       - name: Simple JS Actions
#         id: greet
#         uses: actions/hello-world-javascript-action@v1
#         with:
#           who-to-greet: John

#       - name: Log Greeting Time
#         run: echo "{{ steps.greet.output.time }}"
